---

- hosts: all
  become: true
  tasks:

  - name: Install Apache2 and PHP package on Ubuntu 20 and MC on Ubuntu 18
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution_version == "20.04"

  - name: Install Midnight Commander on Ubuntu 18
    apt:
      name: 
        - mc
      state: latest
      update_cache: yes
    when: ansible_distribution_version == "18.04"

- hosts: file_servers
  become: true
  tasks:

    - name: Install Samba
      apt:
        name:
          - samba
        state: latest
