---

- hosts: all
  become: true
  tasks:

  - name: Update Repository
    apt:
      update_cache: yes

  - name: Remove Apache2 package
    apt:
      name: apache2
      state: latest

  - name: Remove PHP Support for Apache
    apt:
      name: libapache2-mod-php
      state: latest
