- name: Add SSH Key for Andy
  authorized_key:
    user: andy
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMcCiSUX5fksj9qWKEr4wIc7k8j38RO/WaDkJ/JlBi/u Current Ansible Key"


- name: generate sshd_config file from a template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd  
